application: chronostriples
version: 0-2
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /(.*\.(html|js|css|json|png|woff|woff2|ttf))$
  static_files: static/docs/\1
  upload: static/.*\.(html|js|css|json|png|woff|woff2|ttf)$

- url: /docs
  static_files: static/docs/index.html
  upload: static/index.html
  mime_type: text/html

- url: /cron/startcrawling
  script: flankers.scrawler.application
  login: admin

- url: /cron/hrawling
  script: flankers.hrawler.application
  login: admin

- url: /cron/indexing
  script: flankers.indexing.application
  login: admin

- url: /cron/n3caching
  script: flankers.extCaching.application
  login: admin

- url: /cron/storetweets
  script: flankers.tweetStore.application
  login: admin

- url: /cron/storefb
  script: flankers.fbstore.application
  login: admin

- url: /cron/storeyoutube
  script: flankers.youtubestore.application
  login: admin

- url: /remoteapi
  script: google.appengine.ext.remote_api.handler.application
  login: admin

- url: .*
  script: main.application

libraries:
- name: webapp2
  version: "2.5.2"
- name: lxml
  version: "latest"
- name: ssl
  version: latest

builtins:
- remote_api: on
- appstats: off
